version: "3"

services:
  db:
    container_name: postgresql
    image: postgres:14.5-alpine
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=easybill"

  app:
    container_name: easybill
    build: .
    image: arville27/easybill:dev
    depends_on:
      - db
    ports:
      - "9090:9090"
    environment:
      - "APP_ENV=dev"
      - "JDBC_URL=jdbc:postgresql://db:5432/easybill"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
      - "JWT_SECRET=${JWT_SECRET}"
