spring:
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        jdbc.time_zone: UTC
        format_sql: true

easybill:
  token-secret: ${JWT_SECRET}
